name: ğŸ„ Advent of Code Badges ğŸ„
on:
  workflow_dispatch:
  push:
    paths:
      - '**/day*.py' # only if a days source file was modified
jobs:
  build:
    name: â­ Update badges ğŸ“…
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'alasdairnicol') # don't run in forks
    steps:
      - uses: actions/checkout@v2
        # with:
        #  ssh-key: ${{ secrets.SSH_KEY }}
      - uses: joblo2213/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: 2020
      - name: ğŸ“¤ Push
        run: |
          git config --global user.email "<>"
          git config --global user.name "AOC README Bot ğŸ¤–"
          git add .
          git diff-index --quiet HEAD || git commit --message "Update badges on README"
          git push
